import dayjs, { type Dayjs } from 'dayjs'
import type { CalendarEvent, RecurrenceRule } from './types'

/**
 * Recurrence, expanded for the visible range only.
 *
 * The rule the whole module exists to protect: **instances are never
 * materialised into storage.** A weekly standup is one row with a rule, not 520
 * rows — which is the mistake that makes editing a series intractable (change the
 * time and you are rewriting hundreds of records, and "this and following" has no
 * meaning). Storage holds the rule; the views ask for the occurrences that fall in
 * the window they are painting.
 *
 * No RRULE library. The brief's supported subset — daily / weekly by weekday /
 * monthly by date / yearly, with `until` or `count` — is a few dozen lines of
 * dayjs, and `dayjs` stays the only date dependency. What is deliberately NOT
 * supported is the rest of RFC 5545 (BYSETPOS, "last Friday of the month", BYMONTH
 * lists, RDATE); if that is ever wanted, it needs a real library and its own
 * decision.
 *
 * **Weekdays here are Sunday-first**, matching `WEEKDAY_LABELS`, `buildMonthGrid`
 * and `dayjs().day()` — the whole package is Sunday-first. (Clock's alarm mask is
 * Monday-first, because that is how a week reads to a person setting an alarm.
 * The two are not interchangeable and neither should be "unified".)
 */

/** One concrete instance of an event, resolved to real timestamps. */
export type Occurrence = {
  event: CalendarEvent
  /** epoch ms */
  start: number
  /** epoch ms */
  end: number
  /**
   * `YYYY-MM-DD` of this occurrence's start day — the stable identity of an
   * instance within its series, used for exceptions and for React keys. A date
   * rather than an index because inserting an exception must not renumber the
   * occurrences after it.
   */
  occurrenceDate: string
  /** 0 for the first occurrence of the series. */
  index: number
  /** False only for the first occurrence of a recurring event. */
  isRepeat: boolean
}

/**
 * Hard stop on one expansion. A daily rule with no end asked for over a decade
 * would otherwise build ~3650 objects per render; the views never show more than a
 * few hundred, so hitting this cap means the caller asked for too wide a range.
 */
export const MAX_OCCURRENCES = 750

export const ISO_DATE = 'YYYY-MM-DD'

export function occurrenceDateOf(ms: number): string {
  return dayjs(ms).format(ISO_DATE)
}

/** Sunday-first, matching `dayjs().day()` and `WEEKDAY_LABELS`. */
export const WEEKDAY_SHORT = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'] as const

export function describeRule(rule: RecurrenceRule | null): string {
  if (!rule) return 'Does not repeat'
  const every = rule.interval > 1 ? `every ${rule.interval} ` : ''
  let base: string
  switch (rule.freq) {
    case 'daily':
      base = rule.interval > 1 ? `Every ${rule.interval} days` : 'Daily'
      break
    case 'weekly': {
      const days = rule.byWeekday?.length
        ? rule.byWeekday
            .slice()
            .sort((a, b) => a - b)
            .map((d) => WEEKDAY_SHORT[d])
            .join(', ')
        : null
      base = days
        ? `${every ? `Every ${rule.interval} weeks` : 'Weekly'} on ${days}`
        : every
          ? `Every ${rule.interval} weeks`
          : 'Weekly'
      break
    }
    case 'monthly':
      base = rule.interval > 1 ? `Every ${rule.interval} months` : 'Monthly'
      break
    case 'yearly':
      base = rule.interval > 1 ? `Every ${rule.interval} years` : 'Yearly'
      break
  }
  if (rule.count) return `${base}, ${rule.count} times`
  if (rule.until) return `${base}, until ${dayjs(rule.until).format('MMM D, YYYY')}`
  return base
}

/**
 * The start instants of a rule's occurrences, in order, starting from the
 * event's own start.
 *
 * Generated by walking the rule forward rather than by computing an nth date
 * directly, because `count` and `until` both terminate the series and a skipped
 * month (see below) must not consume a count.
 */
function* startInstants(first: Dayjs, rule: RecurrenceRule): Generator<Dayjs> {
  const interval = Math.max(1, Math.trunc(rule.interval))

  if (rule.freq === 'weekly') {
    const wanted =
      rule.byWeekday && rule.byWeekday.length > 0
        ? [...new Set(rule.byWeekday)].sort((a, b) => a - b)
        : [first.day()]
    // Walk week by week from the Sunday of the first occurrence's week, emitting
    // the wanted weekdays in order and skipping anything before the start.
    let weekStart = first.subtract(first.day(), 'day')
    for (;;) {
      for (const day of wanted) {
        const candidate = weekStart
          .add(day, 'day')
          .hour(first.hour())
          .minute(first.minute())
          .second(0)
          .millisecond(0)
        if (!candidate.isBefore(first, 'minute')) yield candidate
      }
      weekStart = weekStart.add(interval, 'week')
    }
  }

  if (rule.freq === 'daily') {
    let cursor = first
    for (;;) {
      yield cursor
      cursor = cursor.add(interval, 'day')
    }
  }

  if (rule.freq === 'monthly') {
    const dayOfMonth = first.date()
    let month = first.startOf('month')
    for (;;) {
      // BYMONTHDAY semantics: a month without that date simply produces nothing.
      // Jan 31 monthly skips February rather than sliding to the 28th, because
      // sliding invents an occurrence on a date the user never chose — and the
      // slid date then differs from every other month in the series.
      if (month.daysInMonth() >= dayOfMonth) {
        const candidate = month
          .date(dayOfMonth)
          .hour(first.hour())
          .minute(first.minute())
          .second(0)
          .millisecond(0)
        if (!candidate.isBefore(first, 'minute')) yield candidate
      }
      month = month.add(interval, 'month')
    }
  }

  if (rule.freq === 'yearly') {
    const month = first.month()
    const dayOfMonth = first.date()
    let year = first.startOf('year')
    for (;;) {
      const target = year.month(month)
      // Same rule as monthly: Feb 29 yearly happens on leap years only.
      if (target.daysInMonth() >= dayOfMonth) {
        const candidate = target
          .date(dayOfMonth)
          .hour(first.hour())
          .minute(first.minute())
          .second(0)
          .millisecond(0)
        if (!candidate.isBefore(first, 'minute')) yield candidate
      }
      year = year.add(interval, 'year')
    }
  }
}

/**
 * Expand one event into the occurrences that overlap `[rangeStart, rangeEnd)`.
 *
 * A non-recurring event yields itself when it overlaps, and nothing otherwise, so
 * callers never have to branch on `event.recurrence`.
 *
 * Overlap, not containment: a three-day event that begins before the range still
 * belongs to it. That is the same reason the views changed — filtering on the
 * start day alone made a multi-day event visible only on its first day.
 */
export function expandOccurrences(
  event: CalendarEvent,
  rangeStart: number,
  rangeEnd: number
): Occurrence[] {
  const durationMs = Math.max(0, event.end - event.start)
  const rule = event.recurrence

  if (!rule) {
    if (event.end < rangeStart || event.start >= rangeEnd) return []
    return [
      {
        event,
        start: event.start,
        end: event.end,
        occurrenceDate: occurrenceDateOf(event.start),
        index: 0,
        isRepeat: false,
      },
    ]
  }

  const exceptions = new Set(event.exceptions)
  const first = dayjs(event.start)
  const untilEnd = rule.until ? dayjs(rule.until).endOf('day').valueOf() : null
  // Whether the series is bounded by its own rule. When it is, the safety cap
  // counts the series index (the whole series is small). When it is NOT, an old
  // no-end rule can have thousands of occurrences BEFORE the visible range, and
  // capping on the index exhausts the budget before reaching the window — the
  // view then shows nothing and reminders stop (T1-5). Cap on the occurrences
  // actually collected in range instead; the `start >= rangeEnd` break still
  // bounds the walk.
  const hasSeriesLimit = rule.count !== undefined || untilEnd !== null
  const out: Occurrence[] = []
  let index = 0

  for (const instant of startInstants(first, rule)) {
    const start = instant.valueOf()
    // Terminate on the rule's own limits before the range check, so `count`
    // counts occurrences of the series and not of the visible window.
    if (untilEnd !== null && start > untilEnd) break
    if (rule.count !== undefined && index >= rule.count) break
    if (hasSeriesLimit ? index >= MAX_OCCURRENCES : out.length >= MAX_OCCURRENCES) break

    const end = start + durationMs
    const date = occurrenceDateOf(start)
    const thisIndex = index
    index++

    // An excepted instance still consumes its index and its count: deleting the
    // third of ten does not promote the fourth into being the third, and "10
    // times" does not become 11. This is deliberately the opposite of a month too
    // short to hold the date (Feb for a "31st" rule), which generates no instance
    // at all and therefore has nothing to consume.
    if (exceptions.has(date)) continue

    if (end < rangeStart) continue
    if (start >= rangeEnd) break

    out.push({
      event,
      start,
      end,
      occurrenceDate: date,
      index: thisIndex,
      isRepeat: thisIndex > 0,
    })
  }

  return out
}

/** Every occurrence of every event overlapping the range, earliest first. */
export function expandAll(
  events: CalendarEvent[],
  rangeStart: number,
  rangeEnd: number
): Occurrence[] {
  return events
    .flatMap((event) => expandOccurrences(event, rangeStart, rangeEnd))
    .sort((a, b) => a.start - b.start || a.end - b.end)
}

/** The occurrences that touch one calendar day, all-day and multi-day included. */
export function occurrencesOnDay(occurrences: Occurrence[], day: Dayjs): Occurrence[] {
  const dayStart = day.startOf('day').valueOf()
  const dayEnd = day.endOf('day').valueOf()
  return occurrences.filter((o) => o.start <= dayEnd && o.end >= dayStart)
}

/** True when the occurrence covers more than the single day it starts on. */
export function spansMultipleDays(o: Occurrence): boolean {
  return !dayjs(o.start).isSame(dayjs(o.end), 'day')
}
